version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: nooors
      POSTGRES_PASSWORD: nooorspwd
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://nooors:nooorspwd@db:5432/taskdb
    depends_on:
      - db
    volumes:
      - ../:/workspace/task-management-app  # Mount the entire project folder
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
